### ISSUE TITLE
About us 2.0

### ISSUE THREAD

**Issue by somtooo** [somtooo/OpenLabs#4]
Better version of the about us page 
![aloko frame](https://user-images.githubusercontent.com/19388476/42756143-ce506f20-88f2-11e8-9da1-63838fc097b5.jpg)
![aloko wireframe](https://user-images.githubusercontent.com/19388476/42756160-dd48dc9c-88f2-11e8-91f5-4ad1681dc653.JPEG)

**Comment by monoblack21** [comment]
use wireframe arrangement
